Repository karafka/karafka, pull requests merged in 2018-06, with the labels that each got.

#364 Too shallow ruby-kafka version lock
  CHANGELOG.md
  Gemfile.lock
  karafka.gemspec
Labels: api-sync, enhancement

#358 values method for params_batch that returns parsed values from the batch
  CHANGELOG.md
  lib/karafka/params/params_batch.rb
  spec/lib/karafka/params/params_batch_spec.rb
Labels: enhancement

#362 Divide mark_as_consumed into mark_as_consumed and mark_as_consumed!
  CHANGELOG.md
  lib/karafka/base_consumer.rb
  lib/karafka/connection/client.rb
  spec/lib/karafka/base_consumer_spec.rb
  spec/lib/karafka/connection/client_spec.rb
Labels: enhancement

#361 Single params consuming mode automatically parses data spec
  CHANGELOG.md
  spec/lib/karafka/consumers/single_params_spec.rb
Labels: bug

#357 Fix a wrong file permission
  .gitignore
  Gemfile
  README.md
  karafka.gemspec
  spec/lib/karafka/schemas/config_spec.rb
  spec/lib/karafka/setup/config_spec.rb
  spec/lib/karafka/version_spec.rb
  spec/lib/karafka_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#367 #354 for 1.3 - expose consumer heartbeat
  lib/karafka/base_consumer.rb
  lib/karafka/connection/client.rb
  spec/lib/karafka/base_consumer_spec.rb
  spec/lib/karafka/connection/client_spec.rb
Labels: api-sync, enhancement
