Repository karafka/karafka, pull requests merged in 2018-04, with the labels that each got.

#307 #306
  CHANGELOG.md
  lib/karafka/server.rb
Labels: bug

#308 cleanup ruby versions
  .travis.yml
Labels: enhancement

#321 #320 and #318
  CHANGELOG.md
  lib/karafka/attributes_map.rb
  lib/karafka/connection/api_adapter.rb
  lib/karafka/connection/client.rb
  lib/karafka/errors.rb
  lib/karafka/schemas/consumer_group.rb
  lib/karafka/setup/config.rb
  spec/lib/karafka/attributes_map_spec.rb
  spec/lib/karafka/connection/api_adapter_spec.rb
  spec/lib/karafka/connection/client_spec.rb
  spec/lib/karafka/schemas/consumer_group_spec.rb
Labels: api-sync, bug, heroku
