Repository karafka/karafka, pull requests merged in 2019-05, with the labels that each got.

#503 bump-gems-2019-05-13
  Gemfile.lock
Labels: self-accepted

#504 forced kill
  CHANGELOG.md
  lib/karafka/server.rb
  spec/lib/karafka/server_spec.rb
Labels: bug

#512 ssl_verify_hostname sync
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/schemas/consumer_group.rb
  lib/karafka/setup/config.rb
  spec/lib/karafka/connection/api_adapter_spec.rb
  spec/lib/karafka/connection/builder_spec.rb
  spec/lib/karafka/schemas/consumer_group_spec.rb
Labels: api-sync
