Repository karafka/karafka, pull requests merged in 2019-04, with the labels that each got.

#484 add additional post stop events
  lib/karafka/instrumentation/monitor.rb
  lib/karafka/server.rb
Labels: enhancement

#488 proctitle listener
  CHANGELOG.md
  lib/karafka/instrumentation/proctitle_listener.rb
  lib/karafka/instrumentation/stdout_listener.rb
  lib/karafka/templates/karafka.rb.example
  spec/lib/karafka/instrumentation/proctitle_listener_spec.rb
  spec/lib/karafka/instrumentation/stdout_listener_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#494 sidekiq backend issue 29
  CHANGELOG.md
  lib/karafka/helpers/class_matcher.rb
  lib/karafka/responders/builder.rb
  spec/lib/karafka/helpers/class_matcher_spec.rb
Labels: bug

#496 use irb
  CHANGELOG.md
  Gemfile.lock
  karafka.gemspec
Labels: bug

#498 bump-gems-2019-04-30
  Gemfile.lock
Labels: self-accepted

#499 zeitwerk setup
  CHANGELOG.md
  Gemfile.lock
  karafka.gemspec
  lib/karafka.rb
  lib/karafka/instrumentation/logger.rb
  lib/karafka/loader.rb
  lib/karafka/routing/builder.rb
  lib/karafka/routing/proxy.rb
  lib/karafka/schemas.rb
  lib/karafka/schemas/config.rb
  lib/karafka/setup/configurators/water_drop.rb
  spec/lib/karafka/loader_spec.rb
  spec/lib/karafka/schemas_spec.rb
Labels: enhancement
