Repository karafka/karafka, pull requests merged in 2022-10, with the labels that each got.

#1051 Multiple consumer group rebalance stability
  spec/integrations/rebalancing/multiple_consumer_groups_stability.rb
Labels: 2.0, specs

#1050 cooperative-sticky rebalance strategy support + offset commit improvements
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/connection/listener.rb
  lib/karafka/connection/rebalance_manager.rb
  lib/karafka/patches/rdkafka/bindings.rb
  spec/integrations/offset_management/rebalance_commit.rb
  spec/integrations/rebalancing/cooperative_sticky.rb
  spec/integrations/rebalancing/exceeding_max_poll_with_fast_commit.rb
  spec/integrations/rebalancing/exceeding_max_poll_with_late_commit.rb
  spec/integrations/rebalancing/multiple_consumer_groups_stability.rb
  spec/lib/karafka/connection/listener_spec.rb
  spec/spec_helper.rb
Labels: enhancement, 2.0, internal

#1052 v2.0.12 release
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/version.rb
Labels: 2.0

#1055 #1053 cooperative-sticky-full-spec
  spec/integrations/rebalancing/cooperative_sticky_full.rb
  spec/integrations_helper.rb
Labels: 2.0, specs

#1060 #1053 - ignore marking as consumed for older offsets
  CHANGELOG.md
  lib/karafka/base_consumer.rb
  spec/integrations/offset_management/with_marking_older_message.rb
  spec/lib/karafka/active_job/consumer_spec.rb
  spec/lib/karafka/base_consumer_spec.rb
  spec/lib/karafka/pro/base_consumer_spec.rb
  spec/support/factories/processing/coordinator.rb
Labels: 2.0, specs, internal

#1066 require concurrent-ruby
  Gemfile.lock
  karafka.gemspec
  lib/karafka.rb
Labels: bug, 1.4

#1065 Provide attributes map for stripping non applicable settings on librdkafka
  CHANGELOG.md
  lib/karafka/routing/subscription_group.rb
  lib/karafka/setup/attributes_map.rb
  lib/karafka/setup/config.rb
  spec/integrations/consumption/with_separate_subscription_groups.rb
  spec/integrations/pausing/pause_early_and_skip_via_marking.rb
  spec/integrations/setup/attributes_distribution.rb
  spec/integrations_helper.rb
  spec/lib/karafka/setup/attributes_map_spec.rb
Labels: enhancement, 2.0, internal

#1067 v1.4.14
  CHANGELOG.md
  Gemfile.lock
  certs/mensfeld.pem
  karafka.gemspec
  lib/karafka/version.rb
Labels: 1.4

#1068 v2.0.13
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/version.rb
Labels: 2.0

#1071 Compensate for first request unpredictability
  bin/integrations
  spec/integrations/rebalancing/exceeding_max_poll_with_late_commit_spec.rb
Labels: 2.0, specs

#1072 Update github actions checkout
  .github/workflows/ci.yml
Labels: 2.0, internal

#1074 Fix a pause-resume-expire race condition for LRJ
  CHANGELOG.md
  lib/karafka/time_trackers/pause.rb
  lib/karafka/time_trackers/poll.rb
Labels: bug, 2.0, internal, lrj

#1075 v2.0.14 release
  CHANGELOG.md
  Gemfile.lock
  bin/integrations
  lib/karafka/version.rb
  spec/integrations/offset_management/with_different_initial_offsets_one_group_spec.rb
Labels: 2.0

#1079 Sanitize config also for admin and rdkafka
  CHANGELOG.md
  lib/karafka/admin.rb
  spec/integrations/pro/rebalancing/with_static_membership_reconnect_spec.rb
  spec/integrations/rebalancing/with_static_membership_reconnect_spec.rb
  spec/integrations_helper.rb
Labels: 2.0, internal

#1082 Per topic lag reporting with trends DD reporting
  lib/karafka/instrumentation/vendors/datadog/dashboard.json
  lib/karafka/instrumentation/vendors/datadog/listener.rb
  spec/integrations/instrumentation/data_dog_integration_flow_spec.rb
Labels: enhancement, 2.0

#1085 consistent VP partioning consumer instance assignment
  CHANGELOG.md
  lib/karafka/pro/processing/partitioner.rb
  spec/integrations/pro/consumption/virtual_partitions/consistent_distribution_spec.rb
  spec/integrations/pro/consumption/virtual_partitions/with_more_vps_than_workers_spec.rb
Labels: bug, 2.0, virtual partitions

#1086 flush spec log sync and spec stability
  spec/integrations/pro/rails/active_job/virtual_partitions/with_partitioning_using_key_spec.rb
  spec/integrations/rebalancing/cooperative_sticky_full_spec.rb
  spec/integrations_helper.rb
Labels: 2.0, specs

#1091 Spec for post error cleaning operations
  spec/integrations/consumption/non_critical_error_post_error_action.rb
  spec/integrations/offset_management/rebalance_commit_spec.rb
Labels: 2.0, specs

#1092 v2.0.15
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/version.rb
Labels: 2.0

#1094 Add consumer_group tag to metrics
  CHANGELOG.md
  lib/karafka/connection/listener.rb
  lib/karafka/instrumentation/vendors/datadog/dashboard.json
  lib/karafka/instrumentation/vendors/datadog/listener.rb
  spec/integrations/installation/standalone_pristine/install_spec.rb
Labels: enhancement, 2.0, instrumentation

#1095 Notification flow fixes
  CHANGELOG.md
  lib/karafka/instrumentation/logger_listener.rb
  spec/lib/karafka/instrumentation/logger_listener_spec.rb
  spec/lib/karafka/instrumentation/monitor_spec.rb
Labels: 2.0

#1097 optimize routing validation flow
  CHANGELOG.md
  config/errors.yml
  lib/karafka/contracts/consumer_group.rb
  lib/karafka/contracts/topic.rb
  lib/karafka/pro/contracts/consumer_group.rb
  lib/karafka/pro/contracts/topic.rb
  lib/karafka/pro/loader.rb
  lib/karafka/pro/routing/builder_extensions.rb
  lib/karafka/routing/builder.rb
  spec/integrations/consumption/with_mixed_subscription_groups_spec.rb
  spec/lib/karafka/contracts/consumer_group_spec.rb
  spec/lib/karafka/contracts/topic_spec.rb
  spec/lib/karafka/pro/contracts/consumer_group_spec.rb
  spec/lib/karafka/pro/contracts/topic_spec.rb
  spec/lib/karafka/pro/routing/builder_extensions_spec.rb
Labels: 2.0, internal, routing

#1103 Migrate strategy selection for regular (non pro) consumption combinations
  CHANGELOG.md
  config/errors.yml
  lib/karafka/base_consumer.rb
  lib/karafka/errors.rb
  lib/karafka/instrumentation/logger_listener.rb
  lib/karafka/processing/coordinator.rb
  lib/karafka/processing/executor.rb
  lib/karafka/processing/strategies/base.rb
  lib/karafka/processing/strategies/default.rb
  lib/karafka/processing/strategies/mom.rb
  lib/karafka/processing/strategy_selector.rb
  lib/karafka/routing/features/active_job/contract.rb
  lib/karafka/routing/features/manual_offset_management/topic.rb
  lib/karafka/setup/config.rb
  spec/integrations/consumption/strategies/default/constant_error_should_not_clog_others_spec.rb
  spec/integrations/consumption/strategies/default/from_earliest_simple_routing_spec.rb
  spec/integrations/consumption/strategies/default/from_earliest_spec.rb
  spec/integrations/consumption/strategies/default/from_latest_with_non_persistent_error_spec.rb
  spec/integrations/consumption/strategies/default/many_topics_same_group_spec.rb
  spec/integrations/consumption/strategies/default/multi_topic_ping_pong_spec.rb
  spec/integrations/consumption/strategies/default/non_constant_error_and_other_topics_spec.rb
  spec/integrations/consumption/strategies/default/non_critical_error_constant_backoff_spec.rb
  spec/integrations/consumption/strategies/default/non_critical_error_exponential_backoff_spec.rb
  spec/integrations/consumption/strategies/default/non_critical_error_pause_no_marking_spec.rb
  spec/integrations/consumption/strategies/default/non_critical_error_pause_position_marking_spec.rb
  spec/integrations/consumption/strategies/default/non_critical_error_post_error_action.rb
  spec/integrations/consumption/strategies/default/non_critical_error_recovery_spec.rb
  spec/integrations/consumption/strategies/default/of_many_partitions_with_error_spec.rb
  spec/integrations/consumption/strategies/default/of_many_partitions_with_many_workers_spec.rb
  spec/integrations/consumption/strategies/default/of_many_topics_on_many_workers_spec.rb
  spec/integrations/consumption/strategies/default/of_many_topics_with_different_settings_spec.rb
  spec/integrations/consumption/strategies/default/of_many_with_error_and_long_pause_spec.rb
  spec/integrations/consumption/strategies/default/of_messages_with_headers_spec.rb
  spec/integrations/consumption/strategies/mom/manual_offset_with_error_every_bang_spec.rb
  spec/integrations/consumption/strategies/mom/manual_offset_with_error_every_non_bang_spec.rb
  spec/integrations/consumption/strategies/mom/manual_offset_with_error_interval_bang_spec.rb
  spec/integrations/consumption/strategies/mom/manual_offset_with_error_interval_non_bang_spec.rb
  spec/integrations/consumption/strategies/mom/with_manual_offset_and_error_spec.rb
  spec/lib/karafka/base_consumer_spec.rb
  spec/lib/karafka/processing/coordinator_spec.rb
  spec/lib/karafka/processing/strategies/base_spec.rb
  spec/lib/karafka/processing/strategies/default_spec.rb
  spec/lib/karafka/processing/strategies/mom_spec.rb
  spec/lib/karafka/processing/strategy_selector_spec.rb
  spec/lib/karafka/routing/features/active_job/contract_spec.rb
  spec/spec_helper.rb
Labels: enhancement, 2.0

#1107 add missing ssl.providers attribute
  lib/karafka/setup/attributes_map.rb
Labels: bug
