Repository karafka/karafka, pull requests merged in 2022-09, with the labels that each got.

#1011 optimize specs supervision
  bin/integrations
Labels: 2.0, specs

#1012 Multi topic ping pong spec #1008
  spec/integrations/consumption/multi_topic_ping_pong.rb
Labels: 2.0, specs

#1013 lrj non-blocking spec
  spec/integrations/pro/consumption/long_running_jobs/parallel_non_lrj_with_lrj.rb
Labels: 2.0, specs

#1016 v2.0.6 release
  CHANGELOG.md
Labels: 2.0

#1018 Improve spec stability on a slow ci
  spec/integrations/pro/rails/active_job/virtual_partitions/from_earliest.rb
  spec/integrations/rebalancing/exceeding_max_poll_interval.rb
Labels: 2.0, specs

#1021 Virtual Partitions limited concurrency
  CHANGELOG.md
  Gemfile.lock
  config/errors.yml
  lib/karafka/pro/active_job/consumer.rb
  lib/karafka/pro/contracts/consumer_group_topic.rb
  lib/karafka/pro/loader.rb
  lib/karafka/pro/processing/partitioner.rb
  lib/karafka/pro/routing/topic_extensions.rb
  lib/karafka/routing/proxy.rb
  lib/karafka/version.rb
  spec/integrations/pro/consumption/virtual_partitions/different_coordinator_different_partitions.rb
  spec/integrations/pro/consumption/virtual_partitions/distributing_work_randomly.rb
  spec/integrations/pro/consumption/virtual_partitions/distributing_work_using_message_keys.rb
  spec/integrations/pro/consumption/virtual_partitions/from_earliest.rb
  spec/integrations/pro/consumption/virtual_partitions/many_batches.rb
  spec/integrations/pro/consumption/virtual_partitions/many_batches_same_key.rb
  spec/integrations/pro/consumption/virtual_partitions/many_distributed_batches_end_order.rb
  spec/integrations/pro/consumption/virtual_partitions/shared_coordinator.rb
  spec/integrations/pro/consumption/virtual_partitions/with_error.rb
  spec/integrations/pro/consumption/virtual_partitions/with_error_on_another_batch.rb
  spec/integrations/pro/consumption/virtual_partitions/with_limited_concurrency.rb
  spec/integrations/pro/consumption/virtual_partitions/with_manual_offset_management.rb
  spec/integrations/pro/consumption/virtual_partitions/with_manual_offset_management_error.rb
  spec/integrations/pro/consumption/virtual_partitions/with_more_vps_than_workers.rb
  spec/integrations/pro/consumption/virtual_partitions/with_parallel_errors.rb
  spec/integrations/pro/consumption/vp_with_lrj_from_earliest.rb
  spec/integrations/pro/rails/active_job/virtual_partitions/from_earliest.rb
  spec/integrations/pro/rails/active_job/virtual_partitions/with_error.rb
  spec/integrations/pro/rails/active_job/virtual_partitions/with_error_on_next_job.rb
  spec/integrations/pro/rails/active_job/virtual_partitions/with_partitioning_using_key.rb
  spec/integrations/pro/rails/active_job/virtual_partitions/with_revocation.rb
  spec/integrations/pro/rebalancing/virtual_partitions/coordinator_replacement_after_rebalance.rb
  spec/integrations/pro/rebalancing/virtual_partitions/rebalance_continuity.rb
  spec/integrations/pro/routing/non_pro_without_virtual_partitioner.rb
  spec/integrations/pro/routing/pro_with_virtual_partitioner.rb
  spec/integrations/pro/shutdown/virtual_partitions/shutdown_on_all_consumers.rb
  spec/lib/karafka/pro/active_job/consumer_spec.rb
  spec/lib/karafka/pro/base_consumer_spec.rb
  spec/lib/karafka/pro/contracts/consumer_group_spec.rb
  spec/lib/karafka/pro/contracts/consumer_group_topic_spec.rb
  spec/lib/karafka/pro/processing/jobs_builder_spec.rb
  spec/lib/karafka/pro/processing/partitioner_spec.rb
  spec/lib/karafka/pro/routing/builder_extensions_spec.rb
  spec/lib/karafka/pro/routing/topic_extensions_spec.rb
Labels: enhancement, 2.0, pro, virtual partitions

#1024 rename VP concurrency to max_partitions
  CHANGELOG.md
  config/errors.yml
  lib/karafka/pro/contracts/consumer_group_topic.rb
  lib/karafka/pro/processing/partitioner.rb
  lib/karafka/pro/routing/topic_extensions.rb
  spec/integrations/pro/consumption/virtual_partitions/with_limited_concurrency.rb
  spec/integrations/pro/consumption/virtual_partitions/with_more_vps_than_workers.rb
  spec/lib/karafka/pro/contracts/consumer_group_spec.rb
  spec/lib/karafka/pro/contracts/consumer_group_topic_spec.rb
Labels: 2.0, pro, virtual partitions

#1025 improve spec stability
  spec/integrations/pro/rebalancing/long_running_jobs/revoke_mark_as_consumed_enough_threads.rb
Labels: 2.0, specs, internal

#1031 allow for block based subscription groups definitions
  CHANGELOG.md
  lib/karafka/routing/builder.rb
  lib/karafka/routing/consumer_group.rb
  spec/integrations/consumption/with_mixed_subscription_groups.rb
  spec/integrations/consumption/with_separate_subscription_groups.rb
  spec/integrations/instrumentation/statistics_on_lag_with_many_sub_group.rb
  spec/integrations/instrumentation/statistics_on_lag_with_one_sub_group.rb
  spec/integrations/routing/routing_with_subscription_groups_arg_based.rb
  spec/integrations/routing/routing_with_subscription_groups_block_based.rb
  spec/lib/karafka/routing/builder_spec.rb
Labels: 2.0, feature

#1029 Fix typo in comment
  lib/karafka/base_consumer.rb
  lib/karafka/pro/base_consumer.rb
  lib/karafka/processing/jobs/base.rb
  lib/karafka/processing/jobs_queue.rb
Labels: documentation, 2.0

#1035 Require singleton directly and include poro specs
  CHANGELOG.md
  bin/integrations
  lib/karafka.rb
  spec/integrations/installation/standalone_pristine/Gemfile
  spec/integrations/installation/standalone_pristine/install.rb
  spec/integrations/installation/with_rails_pristine/Gemfile
  spec/integrations/installation/with_rails_pristine/install.rb
  spec/integrations/pro/licensing/load_poro/Gemfile
  spec/integrations/pro/licensing/load_poro/configure.rb
  spec/integrations/pro/rails/rails5_pristine/Gemfile
  spec/integrations/pro/rails/rails5_pristine/railtie_setup.rb
  spec/integrations/pro/rails/rails6_pristine/Gemfile
  spec/integrations/pro/rails/rails6_pristine/railtie_setup.rb
  spec/integrations/pro/rails/rails7_pristine/Gemfile
  spec/integrations/pro/rails/rails7_pristine/railtie_setup.rb
  spec/integrations/rails/rails5_pristine/Gemfile
  spec/integrations/rails/rails5_pristine/extended_routing_absence.rb
  spec/integrations/rails/rails5_pristine/railtie_setup.rb
  spec/integrations/rails/rails6/just-a-dependency_pristine/Gemfile
  spec/integrations/rails/rails6/just-a-dependency_pristine/rails_setup.rb
  spec/integrations/rails/rails6/with-active_job_pristine/Gemfile
  spec/integrations/rails/rails6/with-active_job_pristine/extended_routing_presence.rb
  spec/integrations/rails/rails6/with-active_job_pristine/railtie_setup.rb
  spec/integrations/rails/rails6/without-a-boot-file_pristine/Gemfile
  spec/integrations/rails/rails6/without-a-boot-file_pristine/railtie_setup.rb
  spec/integrations/rails/rails6/without-active_job_pristine/Gemfile
  spec/integrations/rails/rails6/without-active_job_pristine/extended_routing_absence.rb
  spec/integrations/rails/rails6/without-active_job_pristine/railtie_setup.rb
  spec/integrations/rails/rails6/without-active_job_rspec_pristine/Gemfile
  spec/integrations/rails/rails6/without-active_job_rspec_pristine/rspec_rails_setup.rb
  spec/integrations/rails/rails7/just-a-dependency_pristine/Gemfile
  spec/integrations/rails/rails7/just-a-dependency_pristine/rails_setup.rb
  spec/integrations/rails/rails7/with-active_job_pristine/Gemfile
  spec/integrations/rails/rails7/with-active_job_pristine/extended_routing_absence.rb
  spec/integrations/rails/rails7/with-active_job_pristine/railtie_setup.rb
  spec/integrations/rails/rails7/without-active_job_pristine/Gemfile
  spec/integrations/rails/rails7/without-active_job_pristine/extended_routing_absence.rb
  spec/integrations/rails/rails7/without-active_job_pristine/railtie_setup.rb
  spec/integrations/rails/rails7/without-active_job_rspec_pristine/Gemfile
  spec/integrations/rails/rails7/without-active_job_rspec_pristine/rspec_rails_setup.rb
  spec/integrations/rebalancing/on_partition_data_revoked.rb
Labels: bug, 2.0

#1037 Optimize error handling edge cases + improve routing validation and seek offset notion
  CHANGELOG.md
  config/errors.yml
  lib/karafka/active_job/routing/extensions.rb
  lib/karafka/base_consumer.rb
  lib/karafka/connection/client.rb
  lib/karafka/pro/base_consumer.rb
  lib/karafka/pro/contracts/consumer_group_topic.rb
  lib/karafka/pro/processing/coordinator.rb
  lib/karafka/processing/coordinator.rb
  lib/karafka/routing/topic.rb
  spec/integrations/consumption/non_critical_error_exponential_backoff.rb
  spec/integrations/offset_management/with_manual_offset_and_error.rb
  spec/integrations/pro/consumption/virtual_partitions/with_manual_offset_management.rb
  spec/integrations/pro/consumption/virtual_partitions/with_manual_offset_management_error.rb
  spec/integrations/pro/offset_management/with_manual_offset_and_error.rb
  spec/integrations/pro/routing/virtual_partitions_with_manual_offset_management.rb
  spec/lib/karafka/base_consumer_spec.rb
  spec/lib/karafka/connection/client_spec.rb
  spec/lib/karafka/connection/listeners_batch_spec.rb
  spec/lib/karafka/pro/base_consumer_spec.rb
  spec/lib/karafka/pro/processing/coordinator_spec.rb
  spec/lib/karafka/processing/coordinator_spec.rb
  spec/lib/karafka/routing/topic_spec.rb
  spec/spec_helper.rb
Labels: bug, 2.0

#1039 v2.0.9
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/version.rb
Labels: 2.0

#1040 Fix integration spec type detection
  bin/integrations
  spec/integrations/pro/rebalancing/long_running_jobs/revoke_mark_as_consumed_sync_enough_threads.rb
Labels: bug, 2.0

#1042 Error handling improvements in the polling
  CHANGELOG.md
  lib/karafka/connection/client.rb
  lib/karafka/instrumentation/logger_listener.rb
  lib/karafka/pro/base_consumer.rb
  spec/integrations/pro/rebalancing/long_running_jobs/rebalance_continuity.rb
  spec/lib/karafka/instrumentation/logger_listener_spec.rb
  spec/spec_helper.rb
Labels: enhancement, 2.0, internal

#1043 v2.0.10
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/version.rb
Labels: 2.0

#1044 Improve error notifications on key polling errors
  CHANGELOG.md
  lib/karafka/connection/client.rb
  spec/integrations/rebalancing/exceeding_max_poll_interval.rb
  spec/integrations_helper.rb
Labels: enhancement, 2.0, internal

#1048 Spec out log compaction via tombstone
  Gemfile.lock
  lib/karafka/serialization/json/deserializer.rb
  spec/integrations/consumption/of_a_tombstone_record.rb
  spec/integrations/consumption/of_an_post_tombstone_message.rb
  spec/integrations_helper.rb
Labels: specs

#1049 v2.0.11
  CHANGELOG.md
Labels: 2.0
