Repository karafka/karafka, pull requests merged in 2022-11, with the labels that each got.

#1104 Migration of Pro feature handling with strategies
  .github/workflows/ci.yml
  .rspec
  CHANGELOG.md
  Gemfile.lock
  bin/rspecs
  lib/karafka.rb
  lib/karafka/pro/base_consumer.rb
  lib/karafka/pro/loader.rb
  lib/karafka/pro/processing/coordinator.rb
  lib/karafka/pro/processing/strategies/aj_lrj_mom.rb
  lib/karafka/pro/processing/strategies/aj_lrj_mom_vp.rb
  lib/karafka/pro/processing/strategies/aj_mom.rb
  lib/karafka/pro/processing/strategies/aj_mom_vp.rb
  lib/karafka/pro/processing/strategies/base.rb
  lib/karafka/pro/processing/strategies/default.rb
  lib/karafka/pro/processing/strategies/lrj.rb
  lib/karafka/pro/processing/strategies/lrj_mom.rb
  lib/karafka/pro/processing/strategies/lrj_vp.rb
  lib/karafka/pro/processing/strategies/mom.rb
  lib/karafka/pro/processing/strategies/mom_vp.rb
  lib/karafka/pro/processing/strategies/vp.rb
  lib/karafka/pro/processing/strategy_selector.rb
  lib/karafka/processing/strategy_selector.rb
  spec/integrations/pro/licensing/configure_with_invalid_token_spec.rb
  spec/integrations/pro/licensing/configure_with_valid_token_spec.rb
  spec/lib/karafka/pro/active_job/consumer_spec.rb
  spec/lib/karafka/pro/base_consumer_spec.rb
  spec/lib/karafka/pro/loader_spec.rb
  spec/lib/karafka/pro/processing/jobs_builder_spec.rb
  spec/lib/karafka/pro/processing/partitioner_spec.rb
  spec/lib/karafka/pro/processing/strategies/aj_lrj_mom_spec.rb
  spec/lib/karafka/pro/processing/strategies/aj_lrj_mom_vp_spec.rb
  spec/lib/karafka/pro/processing/strategies/aj_mom_spec.rb
  spec/lib/karafka/pro/processing/strategies/aj_mom_vp_spec.rb
  spec/lib/karafka/pro/processing/strategies/base_spec.rb
  spec/lib/karafka/pro/processing/strategies/default_spec.rb
  spec/lib/karafka/pro/processing/strategies/lrj_mom_spec.rb
  spec/lib/karafka/pro/processing/strategies/lrj_spec.rb
  spec/lib/karafka/pro/processing/strategies/lrj_vp_spec.rb
  spec/lib/karafka/pro/processing/strategies/mom_spec.rb
  spec/lib/karafka/pro/processing/strategies/mom_vp_spec.rb
  spec/lib/karafka/pro/processing/strategies/vp_spec.rb
  spec/lib/karafka/pro/processing/strategy_selector_spec.rb
  spec/lib/karafka/pro/routing/features/long_running_job/topic_spec.rb
  spec/lib/karafka/pro/routing/features/virtual_partitions/topic_spec.rb
  spec/spec_helper.rb
  spec/support/rspec_locator.rb
Labels: 2.0, pro

#1118 transfer topic in the dlq headers
  lib/karafka/pro/processing/strategies/dlq.rb
  spec/integrations/pro/consumption/strategies/dlq/details_dispatch_transfer_spec.rb
Labels: 2.0, pro, dead letter queue

#1121 Use offset marking on AJ DLQ MOM for regular after DLQ message dispatch
  lib/karafka/processing/strategies/aj_dlq_mom.rb
  lib/karafka/processing/strategies/aj_mom.rb
  lib/karafka/processing/strategy_selector.rb
  spec/integrations/consumption/strategies/aj_mom/backoff_and_retry_on_error_spec.rb
  spec/integrations/consumption/strategies/aj_mom/big_batch_shutdown_early_break_spec.rb
  spec/integrations/consumption/strategies/aj_mom/dispatching_async_job_spec.rb
  spec/integrations/consumption/strategies/aj_mom/dispatching_sync_job_spec.rb
  spec/integrations/consumption/strategies/aj_mom/invalid_configuration_attempt_spec.rb
  spec/integrations/consumption/strategies/aj_mom/multiple_jobs_same_topic_spec.rb
  spec/integrations/consumption/strategies/aj_mom/processing_all_on_shutdown_spec.rb
  spec/integrations/consumption/strategies/aj_mom_dlq/offset_skip_on_non_recoverable_error_spec.rb
  spec/integrations/consumption/strategies/aj_mom_dlq/processing_on_non_recoverable_error_spec.rb
  spec/integrations_helper.rb
  spec/lib/karafka/processing/strategies/aj_dlq_mom_spec.rb
  spec/lib/karafka/processing/strategies/aj_mom_spec.rb
  spec/lib/karafka/processing/strategy_selector_spec.rb
Labels: enhancement, 2.0, activejob, dead letter queue

#1098 Create a Datadog::LoggerListener based on the Karafka::Instrumentation::LoggerListener
  lib/karafka/instrumentation/vendors/datadog/logger_listener.rb
Labels: 2.0, instrumentation

#1123 Improve spec stability
  spec/integrations/rebalancing/multiple_consumer_groups_stability_spec.rb
Labels: 2.0, specs

#1125 missing docs and small remarks
  lib/karafka/pro/processing/strategies/aj_dlq_mom.rb
  lib/karafka/processing/strategies/aj_dlq_mom.rb
  spec/integrations/rebalancing/cooperative_sticky_full_spec.rb
Labels: 2.0, internal

#1122 Datadog::LoggerListener instrumentation
  CHANGELOG.md
  lib/karafka/instrumentation/logger_listener.rb
  lib/karafka/instrumentation/vendors/datadog/logger_listener.rb
  spec/integrations/instrumentation/datadog_logger_flow_spec.rb
  spec/integrations/instrumentation/datadog_metrics_flow_spec.rb
  spec/lib/karafka/instrumentation/vendors/datadog/logger_listener_spec.rb
  spec/support/statsd_dummy_client.rb
  spec/support/vendors/datadog/logger_dummy_client.rb
  spec/support/vendors/datadog/statsd_dummy_client.rb
Labels: enhancement, 2.0, instrumentation

#1131 Release stale AR connections on work finished
  CHANGELOG.md
  lib/karafka/railtie.rb
Labels: enhancement, 2.0, internal

#1132 Increase traceability by priting tracker data on execution expired
  spec/integrations/pro/consumption/strategies/dlq/without_intermediate_marking_spec.rb
  spec/integrations_helper.rb
Labels: 2.0, specs, internal

#1133 include seek_offset in the event payload
  CHANGELOG.md
  lib/karafka/base_consumer.rb
  spec/integrations/consumption/strategies/dlq/without_intermediate_marking_spec.rb
  spec/integrations/consumption/with_error_for_seek_offset_tracking_spec.rb
  spec/integrations/shutdown/on_hanging_listener_and_shutdown_spec.rb
Labels: enhancement, 2.0, instrumentation

#1135 Improve spec stability
  lib/karafka/pro/processing/strategies/aj_dlq_mom.rb
  lib/karafka/pro/processing/strategies/dlq.rb
  lib/karafka/pro/processing/strategies/dlq_lrj.rb
  lib/karafka/pro/processing/strategies/dlq_lrj_mom.rb
  lib/karafka/pro/processing/strategies/dlq_mom.rb
  lib/karafka/processing/strategies/aj_dlq_mom.rb
  lib/karafka/processing/strategies/dlq.rb
  lib/karafka/processing/strategies/dlq_mom.rb
  spec/integrations/consumption/strategies/dlq/manual_dispatch_to_dlq_spec.rb
  spec/integrations/pausing/pause_early_and_skip_via_marking_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/manual_dispatch_to_dlq_spec.rb
  spec/integrations/shutdown/shutdown_jobs_exceeding_max_poll_interval_spec.rb
Labels: 2.0, specs

#1137 Fix invalid shutdown state
  CHANGELOG.md
  lib/karafka/errors.rb
  lib/karafka/server.rb
  lib/karafka/setup/attributes_map.rb
  spec/lib/karafka/instrumentation/logger_listener_spec.rb
  spec/lib/karafka/server_spec.rb
Labels: bug, 2.0

#1136 v2.0.16
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/version.rb
Labels: 2.0

#1141 Fix typo
  lib/karafka/instrumentation/logger_listener.rb
  lib/karafka/routing/features/dead_letter_queue/topic.rb
Labels: 2.0, internal

#1142 Fix unintentional headers naming
  CHANGELOG.md
  lib/karafka/pro/processing/strategies/dlq.rb
  spec/integrations/pro/consumption/strategies/aj_dlq_lrj_mom/with_non_recoverable_slow_jobs_error_spec.rb
  spec/integrations/pro/consumption/strategies/aj_dlq_mom/with_non_recoverable_job_error_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/details_dispatch_transfer_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/manual_dispatch_to_dlq_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/multi_partition_source_target_flow_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/original_offset_tracking_spec.rb
  spec/integrations/pro/consumption/strategies/dlq_lrj/fast_with_non_recoverable_errors_spec.rb
  spec/integrations/pro/consumption/strategies/dlq_lrj/with_non_recoverable_slow_error_spec.rb
  spec/integrations/pro/consumption/strategies/dlq_lrj_mom/with_non_recoverable_slow_no_marking_error_spec.rb
Labels: 2.0, pro, dead letter queue

#1149 caching bundler breaks integrations
  .github/workflows/ci.yml
Labels: 2.0, specs

#1152 Trigger revocation during running shutdown on LRJ
  CHANGELOG.md
  lib/karafka/connection/listener.rb
  spec/integrations/pro/shutdown/long_running_jobs/revocation_awareness_on_shutdown_spec.rb
Labels: enhancement, 2.0, pro, lrj

#1153 #1151 Quiet
  CHANGELOG.md
  lib/karafka/connection/client.rb
  lib/karafka/connection/listener.rb
  lib/karafka/embedded.rb
  lib/karafka/instrumentation/logger_listener.rb
  lib/karafka/instrumentation/notifications.rb
  lib/karafka/instrumentation/vendors/datadog/logger_listener.rb
  lib/karafka/process.rb
  lib/karafka/server.rb
  lib/karafka/status.rb
  spec/integrations/embedding/quiet_spec.rb
  spec/integrations/signals/on_sigtstp_spec.rb
  spec/lib/karafka/instrumentation/logger_listener_spec.rb
  spec/lib/karafka/process_spec.rb
Labels: 2.0, feature

#1156 Optimize shutdown
  CHANGELOG.md
  lib/karafka/app.rb
  lib/karafka/connection/consumer_group_status.rb
  lib/karafka/connection/listener.rb
  lib/karafka/connection/listeners_batch.rb
  lib/karafka/errors.rb
  spec/integrations/consumption/strategies/default/of_many_topics_with_different_settings_spec.rb
  spec/integrations/consumption/with_mixed_performance_in_subscription_group_spec.rb
  spec/integrations/routing/routing_with_anonymous_subscription_group_spec.rb
  spec/integrations/routing/routing_with_subscription_groups_arg_based_spec.rb
  spec/integrations/routing/routing_with_subscription_groups_block_based_spec.rb
  spec/lib/karafka/connection/consumer_group_status_spec.rb
  spec/lib/karafka/connection/listener_spec.rb
  spec/lib/karafka/connection/listeners_batch_spec.rb
  spec/lib/karafka/errors_spec.rb
  spec/lib/karafka/instrumentation/logger_listener_spec.rb
Labels: bug, 2.0

#1158 Optimized LRJ VP revoked awareness + small concurrency improvements
  CHANGELOG.md
  lib/karafka/connection/listener.rb
  lib/karafka/pro/processing/coordinator.rb
  lib/karafka/processing/jobs_queue.rb
  spec/integrations/pro/consumption/strategies/lrj/starved_revocation_on_rebalance_spec.rb
Labels: 2.0, pro, lrj

#1161 Rails integration improvements + shutdown improvements
  CHANGELOG.md
  lib/active_job/karafka.rb
  lib/karafka/connection/client.rb
  lib/karafka/connection/consumer_group_coordinator.rb
  lib/karafka/connection/consumer_group_status.rb
  lib/karafka/connection/listener.rb
  lib/karafka/connection/listeners_batch.rb
  lib/karafka/railtie.rb
  lib/karafka/setup/attributes_map.rb
  spec/integrations/consumption/reaching_max_wait_time_spec.rb
  spec/integrations/instrumentation/statistics_callback_on_client_change_spec.rb
  spec/lib/karafka/connection/consumer_group_coordinator_spec.rb
  spec/lib/karafka/connection/consumer_group_status_spec.rb
  spec/lib/karafka/connection/listener_spec.rb
Labels: 2.0, activejob, rails

#1162 Remove unused constant
  CHANGELOG.md
  lib/karafka/errors.rb
  spec/lib/karafka/errors_spec.rb
  spec/support/data_collector.rb
Labels: 2.0

#1163 meta links
  karafka.gemspec
Labels: 2.0

#1165 1164 skip messages on DLQ
  CHANGELOG.md
  lib/karafka/connection/client.rb
  lib/karafka/pro/performance_tracker.rb
  lib/karafka/pro/processing/strategies/aj_dlq_mom.rb
  lib/karafka/pro/processing/strategies/dlq.rb
  lib/karafka/pro/processing/strategies/dlq_lrj.rb
  lib/karafka/pro/processing/strategies/dlq_lrj_mom.rb
  lib/karafka/pro/processing/strategies/dlq_mom.rb
  lib/karafka/processing/jobs_queue.rb
  lib/karafka/routing/features/dead_letter_queue/contract.rb
  lib/karafka/routing/features/dead_letter_queue/topic.rb
  spec/integrations/pro/consumption/strategies/aj_dlq_lrj_mom/without_dispatch_to_dlq_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/without_dispatch_with_retries_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/without_dispatch_without_retries_spec.rb
  spec/integrations/shutdown/on_hanging_listener_and_shutdown_spec.rb
  spec/integrations_helper.rb
  spec/lib/karafka/routing/features/dead_letter_queue/contract_spec.rb
  spec/support/data_collector.rb
Labels: 2.0, pro, dead letter queue

#1166 v2.0.19
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/version.rb
Labels: 2.0

#1168 use 2.0.4 karafka-core
  Gemfile.lock
  karafka.gemspec
Labels: api-sync, 2.0, internal

#1169 improve unstable spec
  spec/integrations/pro/rebalancing/long_running_jobs/revoke_mark_as_consumed_not_enough_threads_spec.rb
Labels: 2.0, specs

#1174 Support of static group membership with multiple subscription groups
  CHANGELOG.md
  lib/karafka/routing/subscription_group.rb
  spec/integrations/consumption/strategies/default/attempts_tracking_without_errors_spec.rb
  spec/integrations/consumption/strategies/dlq_mom/attempts_tracking_without_errors_spec.rb
  spec/integrations/consumption/with_static_group_of_many_subscriptions_spec.rb
  spec/integrations/pro/consumption/strategies/lrj/attempts_tracking_with_errors_spec.rb
  spec/integrations/pro/consumption/strategies/lrj/attempts_tracking_with_non_recoverable_errors_spec.rb
  spec/integrations/pro/consumption/strategies/lrj/attempts_tracking_without_errors_spec.rb
  spec/integrations/pro/consumption/strategies/lrj/with_never_ending_error_spec.rb
  spec/integrations/pro/consumption/strategies/vp/with_headers_usage_spec.rb
  spec/integrations/pro/consumption/with_never_ending_error_spec.rb
Labels: enhancement, 2.0

#1175 Stabilize group ids
  lib/karafka/routing/builder.rb
  lib/karafka/routing/consumer_group.rb
  lib/karafka/routing/subscription_group.rb
  lib/karafka/routing/subscription_groups_builder.rb
  spec/integrations/routing/routing_with_subscription_groups_arg_based_spec.rb
  spec/integrations/routing/routing_with_subscription_groups_block_based_spec.rb
  spec/integrations/routing/routing_with_subscription_groups_chaotic_order_spec.rb
  spec/integrations/routing/stable_with_subscription_groups.rb
  spec/lib/karafka/routing/builder_spec.rb
  spec/lib/karafka/routing/subscription_group_spec.rb
  spec/lib/karafka/routing/subscription_groups_builder_spec.rb
  spec/support/factories/routing/subscription_group.rb
  spec/support/factories/routing/topic.rb
Labels: bug, 2.0

#1176 v2.0.20
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/version.rb
Labels: 2.0

#1178 illustrate lrj saturation
  spec/integrations/pro/consumption/strategies/lrj/saturated_before_revocation_spec.rb
Labels: 2.0, specs

#1180 update gem description
  karafka.gemspec
Labels: 2.0, internal

#1184 Stabilize spec
  spec/integrations/pausing/pause_early_and_skip_via_marking_spec.rb
Labels: 2.0, internal

#1185 v2.0.21
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/version.rb
Labels: 2.0

#1193 Few small fixes and remarks
  CHANGELOG.md
  config/errors.yml
  lib/karafka/cli/info.rb
  lib/karafka/contracts/topic.rb
  lib/karafka/routing/builder.rb
  spec/integrations/routing/routing_with_symbol_based_subscription_group.rb
  spec/lib/karafka/active_job/consumer_spec.rb
  spec/lib/karafka/cli/info_spec.rb
  spec/lib/karafka/contracts/topic_spec.rb
  spec/lib/karafka/server_spec.rb
Labels: 2.0

#1195 Move consumption to strategies
  lib/karafka/base_consumer.rb
  lib/karafka/pro/processing/strategies/default.rb
  lib/karafka/processing/strategies/base.rb
  lib/karafka/processing/strategies/default.rb
Labels: 2.0, internal

#1197 Fix subscription groups instability
  CHANGELOG.md
  lib/karafka/app.rb
  lib/karafka/routing/consumer_group.rb
  spec/integrations/routing/routing_with_nameless_subscription_groups_spec.rb
  spec/integrations/routing/routing_with_symbol_based_subscription_group_spec.rb
  spec/integrations/routing/stable_with_limited_consumer_groups_spec.rb
  spec/integrations/routing/stable_with_subscription_groups_spec.rb
Labels: bug, 2.0, internal

#1198 Allow running particular named subscription groups and topics similar to consumer groups
  CHANGELOG.md
  config/errors.yml
  lib/karafka/app.rb
  lib/karafka/cli/server.rb
  lib/karafka/contracts/server_cli_options.rb
  lib/karafka/processing/jobs_queue.rb
  lib/karafka/routing/consumer_group.rb
  lib/karafka/routing/subscription_group.rb
  lib/karafka/routing/topic.rb
  lib/karafka/routing/topics.rb
  lib/karafka/server.rb
  lib/karafka/setup/config.rb
  spec/integrations/consumption/two_consumer_groups_one_active_spec.rb
  spec/integrations/routing/limited_scope/with_non_existing_consumer_groups_spec.rb
  spec/integrations/routing/limited_scope/with_non_existing_subscription_groups_spec.rb
  spec/integrations/routing/limited_scope/with_non_existing_topics_spec.rb
  spec/integrations/routing/limited_scope/with_nothing_to_run_spec.rb
  spec/integrations/routing/routing_and_cli_validation_spec.rb
  spec/integrations/routing/stable_with_limited_consumer_groups_spec.rb
  spec/integrations/setup/attributes_distribution_spec.rb
  spec/lib/karafka/app_spec.rb
  spec/lib/karafka/cli/server_spec.rb
  spec/lib/karafka/contracts/server_cli_options_spec.rb
  spec/lib/karafka/routing/consumer_group_spec.rb
  spec/lib/karafka/routing/subscription_group_spec.rb
  spec/lib/karafka/routing/topic_spec.rb
  spec/lib/karafka/routing/topics_spec.rb
  spec/lib/karafka/server_spec.rb
  spec/lib/karafka/setup/dsl_spec.rb
  spec/spec_helper.rb
Labels: 2.0, routing

#1200 Fix duplicated logs in development environment
  CHANGELOG.md
  bin/integrations
  lib/karafka/railtie.rb
  spec/integrations/pro/rails/rails5_pristine/railtie_setup_spec.rb
  spec/integrations/pro/rails/rails6_pristine/railtie_setup_spec.rb
  spec/integrations/pro/rails/rails7_pristine/railtie_setup_spec.rb
  spec/integrations/rails/rails5_pristine/extended_routing_absence_spec.rb
  spec/integrations/rails/rails5_pristine/railtie_setup_spec.rb
  spec/integrations/rails/rails6_pristine/just-a-dependency/Gemfile
  spec/integrations/rails/rails6_pristine/just-a-dependency/rails_setup_spec.rb
  spec/integrations/rails/rails6_pristine/with-active_job/Gemfile
  spec/integrations/rails/rails6_pristine/with-active_job/extended_routing_presence_spec.rb
  spec/integrations/rails/rails6_pristine/with-active_job/railtie_setup_spec.rb
  spec/integrations/rails/rails6_pristine/without-a-boot-file/Gemfile
  spec/integrations/rails/rails6_pristine/without-a-boot-file/railtie_setup_spec.rb
  spec/integrations/rails/rails6_pristine/without-active_job/Gemfile
  spec/integrations/rails/rails6_pristine/without-active_job/extended_routing_absence_spec.rb
  spec/integrations/rails/rails6_pristine/without-active_job/railtie_setup_spec.rb
  spec/integrations/rails/rails6_pristine/without-active_job_rspec/Gemfile
  spec/integrations/rails/rails6_pristine/without-active_job_rspec/rspec_rails_setup_spec.rb
  spec/integrations/rails/rails7_pristine/just-a-dependency/Gemfile
  spec/integrations/rails/rails7_pristine/just-a-dependency/rails_setup_spec.rb
  spec/integrations/rails/rails7_pristine/just-a-dependency/with_potential_name_collision_spec.rb
  spec/integrations/rails/rails7_pristine/with-active_job/Gemfile
  spec/integrations/rails/rails7_pristine/with-active_job/extended_routing_absence_spec.rb
  spec/integrations/rails/rails7_pristine/with-active_job/railtie_setup_spec.rb
  spec/integrations/rails/rails7_pristine/with-active_job/without_double_logging_spec.rb
  spec/integrations/rails/rails7_pristine/without-active_job/Gemfile
  spec/integrations/rails/rails7_pristine/without-active_job/extended_routing_absence_spec.rb
  spec/integrations/rails/rails7_pristine/without-active_job/railtie_setup_spec.rb
  spec/integrations/rails/rails7_pristine/without-active_job_rspec/Gemfile
  spec/integrations/rails/rails7_pristine/without-active_job_rspec/rspec_rails_setup_spec.rb
Labels: bug, 2.0, rails
