Repository karafka/karafka, pull requests merged in 2023-09, with the labels that each got.

#1593 Admin config
  CHANGELOG.md
  config/locales/errors.yml
  lib/karafka/admin.rb
  lib/karafka/contracts/config.rb
  lib/karafka/setup/config.rb
  spec/integrations/setup/admin_invalid_configuration_spec.rb
  spec/lib/karafka/contracts/config_spec.rb
Labels: admin

#1597 1596 - do not crash on non-regexp patterns prior to contracts validation
  CHANGELOG.md
  Gemfile.lock
  karafka.gemspec
  lib/karafka/pro/routing/features/patterns/pattern.rb
  lib/karafka/version.rb
  spec/integrations/pro/routing/patterns/anonymous_with_invalid_regexp_spec.rb
  spec/integrations/pro/routing/patterns/named_with_invalid_regexp_spec.rb
Labels: bug

#1606 Routing defaults
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/routing/builder.rb
  lib/karafka/routing/consumer_group.rb
  lib/karafka/routing/proxy.rb
  lib/karafka/version.rb
  spec/integrations/routing/with_defaults_configured_spec.rb
Labels: routing

#1609 Fix read_topic admin time based lookups
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/admin.rb
  lib/karafka/version.rb
  spec/lib/karafka/admin_spec.rb
Labels: bug, admin

#1612 Compensate for cluster time drift in reporting
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/messages/builders/batch_metadata.rb
  lib/karafka/version.rb
  spec/integrations/consumption/with_future_messages_due_to_drift_spec.rb
  spec/integrations/pro/instrumentation/first_idle_messages_metadata_spec.rb
  spec/integrations/web/from_earliest_drifted_spec.rb
  spec/lib/karafka/messages/builders/batch_metadata_spec.rb
Labels: enhancement, instrumentation

#1614 Stabilize few specs
  bin/integrations
  spec/integrations/consumption/with_future_messages_due_to_drift_spec.rb
  spec/integrations/web/from_earliest_drifted_spec.rb
  spec/lib/karafka/processing/jobs_queue_spec.rb
  spec/lib/karafka/processing/worker_spec.rb
Labels: specs, internal

#1618 Optimize spec
  spec/integrations/consumption/with_non_existing_topics_no_auto_create_spec.rb
Labels: specs, internal

#1619 spec for revoked paused usage
  spec/integrations/pausing/manual_pause_on_a_revoked_partition_spec.rb
Labels: specs, internal

#1623 Migrate to Rails 7.1+ connection cleaning API
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/railtie.rb
  lib/karafka/version.rb
Labels: api-sync, rails

#1626 Untangle routing subscription group reference
  .github/workflows/ci.yml
  CHANGELOG.md
  bin/benchmarks
  bin/integrations
  bin/wait_for_kafka
  config/locales/errors.yml
  docker-compose.yml
  lib/karafka/base_consumer.rb
  lib/karafka/connection/client.rb
  lib/karafka/contracts/topic.rb
  lib/karafka/pro/routing/features/patterns/detector.rb
  lib/karafka/routing/consumer_group.rb
  lib/karafka/routing/subscription_group.rb
  lib/karafka/routing/subscription_groups_builder.rb
  lib/karafka/routing/topic.rb
  spec/integrations/consumption/with_producer_disconnect_error_spec.rb
  spec/integrations/lags/consumption_delayed_spec.rb
  spec/integrations/lags/processing_not_enough_threads_spec.rb
  spec/integrations/pro/consumption/patterns/postfix_match_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/ftr_mom_vp/time_limit_check_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/ftr_vp/time_limit_check_spec.rb
  spec/integrations/pro/consumption/strategies/lrj/ftr_mom_vp/with_continuous_error_spec.rb
  spec/integrations/pro/consumption/strategies/lrj/ftr_mom_vp/with_never_ending_error_spec.rb
  spec/integrations/pro/consumption/strategies/mom/ftr_vp/marking_ahead_with_no_previous_in_batch_start_spec.rb
  spec/integrations/pro/consumption/strategies/mom/ftr_vp/with_reversed_offsets_marking_and_error_spec.rb
  spec/integrations/pro/consumption/strategies/mom/vp/marking_ahead_with_no_previous_in_batch_start_spec.rb
  spec/integrations/pro/consumption/strategies/mom/vp/with_reversed_offsets_marking_and_error_spec.rb
  spec/integrations/pro/rails/active_job/ordered_jobs_with_key_spec.rb
  spec/integrations/rails/rails7_pristine/with-active_job_and_current_attributes/resource_accesibility_and_isolation_spec.rb
  spec/integrations/routing/routing_with_subscription_groups_arg_based_spec.rb
  spec/integrations/routing/routing_with_subscription_groups_block_based_spec.rb
  spec/integrations/shutdown/shutdown_jobs_exceeding_max_poll_interval_spec.rb
  spec/integrations_helper.rb
  spec/lib/karafka/contracts/topic_spec.rb
  spec/lib/karafka/routing/builder_spec.rb
  spec/lib/karafka/routing/subscription_group_spec.rb
  spec/lib/karafka/routing/subscription_groups_builder_spec.rb
  spec/lib/karafka/routing/topic_spec.rb
Labels: internal, routing

#1630 add integration for custom events via karafka monitor
  spec/integrations/instrumentation/custom_events_spec.rb
Labels: specs, internal

#1631 use zookeeper timetick default
  docker-compose.yml
Labels: internal

#1624 use nil? instead of present? on DataDog::Tracing::SpanOperation
  lib/karafka/instrumentation/vendors/datadog/logger_listener.rb
  spec/support/vendors/datadog/logger_dummy_client.rb
Labels: bug, instrumentation

#1635 Add an integration spec illustrating how virtual partitioner that distributes all to one partition cancels VPs
  bin/integrations
  docker-compose.yml
  spec/integrations/consumption/strategies/default/of_many_partitions_with_many_workers_spec.rb
  spec/integrations/lags/processing_not_enough_threads_spec.rb
  spec/integrations/pro/consumption/strategies/aj/dlq_ftr_mom_vp/regular_processing_without_errors_spec.rb
  spec/integrations/pro/consumption/strategies/ftr/static_throttler_spec.rb
  spec/integrations/pro/consumption/strategies/vp/cancelled_vps_due_to_bad_partitioning_spec.rb
  spec/integrations/pro/consumption/strategies/vp/with_error_in_the_middle_marking_spec.rb
  spec/integrations_helper.rb
Labels: specs, internal, virtual partitions

#1637 Split integrations into OSS and Pro and retry Docker
  .github/workflows/ci.yml
  bin/integrations
  spec/integrations/pro/consumption/strategies/ftr/static_throttler_spec.rb
  spec/integrations/pro/rails/rails6_pristine/Gemfile
  spec/integrations/pro/rails/rails6_pristine/railtie_setup_spec.rb
  spec/integrations/pro/rails/rails7_pristine/just_a_dependency/Gemfile
  spec/integrations/pro/rails/rails7_pristine/just_a_dependency/railtie_setup_spec.rb
  spec/integrations/pro/rails/rails7_pristine/with-active_job_and_current_attributes/Gemfile
  spec/integrations/rails/rails6_pristine/just-a-dependency/Gemfile
  spec/integrations/rails/rails6_pristine/with-active_job/Gemfile
  spec/integrations/rails/rails6_pristine/with-active_job/railtie_setup_spec.rb
  spec/integrations/rails/rails6_pristine/without-a-boot-file/Gemfile
  spec/integrations/rails/rails6_pristine/without-active_job/Gemfile
  spec/integrations/rails/rails6_pristine/without-active_job/railtie_setup_spec.rb
  spec/integrations/rails/rails6_pristine/without-active_job_rspec/Gemfile
  spec/integrations/rails/rails7_pristine/just-a-dependency/Gemfile
  spec/integrations/rails/rails7_pristine/with-active_job/Gemfile
  spec/integrations/rails/rails7_pristine/with-active_job/railtie_setup_spec.rb
  spec/integrations/rails/rails7_pristine/with-active_job_and_current_attributes/Gemfile
  spec/integrations/rails/rails7_pristine/without-active_job/Gemfile
  spec/integrations/rails/rails7_pristine/without-active_job/railtie_setup_spec.rb
  spec/integrations/rails/rails7_pristine/without-active_job_rspec/Gemfile
Labels: specs

#1634 Add integrations for dd client
  CHANGELOG.md
  spec/integrations/instrumentation/vendors/datadog/with_original_client_pristine/Gemfile
  spec/integrations/instrumentation/vendors/datadog/with_original_client_pristine/with_proper_ddtrace_spec.rb
Labels: specs, instrumentation

#1639 Retry watermark offsets reading for lack of leader of partition
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/admin.rb
  lib/karafka/version.rb
Labels: admin

#1641 Fix spec condition
  spec/integrations/pro/consumption/strategies/vp/with_error_in_the_middle_marking_spec.rb
Labels: specs, internal

#1642 Add 3.3.0 preview 2 to CI
  .github/workflows/ci.yml
  lib/karafka/setup/attributes_map.rb
  spec/integrations/installation/with_rails_pristine/install_spec.rb
  spec/integrations/rebalancing/with_static_membership_reconnect_spec.rb
Labels: specs
