Repository karafka/karafka, pull requests merged in 2023-08, with the labels that each got.

#1534 Partial manual dlq misuse
  spec/integrations/consumption/strategies/dlq/partial_manual_dlq_with_out_of_scope_crashes_spec.rb
Labels: specs, internal, 2.1

#1536 lower noisy default waterdrop setup
  CHANGELOG.md
  Gemfile.lock
  karafka.gemspec
  lib/karafka/templates/karafka.rb.erb
  lib/karafka/version.rb
Labels: enhancement, 2.1

#1537 stabilize spec
  spec/integrations/pro/consumption/strategies/vp/with_pause_on_collapsed_spec.rb
Labels: specs, internal, 2.1

#1539 Per topic backoff policies
  CHANGELOG.md
  config/locales/pro_errors.yml
  lib/karafka/connection/listener.rb
  lib/karafka/connection/pauses_manager.rb
  lib/karafka/pro/routing/features/pausing.rb
  lib/karafka/pro/routing/features/pausing/contract.rb
  lib/karafka/pro/routing/features/pausing/topic.rb
  lib/karafka/processing/coordinators_buffer.rb
  lib/karafka/routing/topic.rb
  spec/integrations/pro/pausing/with_per_topic_pause_setup_spec.rb
  spec/integrations/pro/routing/pausing/with_custom_invalid_pausing_spec.rb
  spec/integrations/pro/routing/pausing/with_custom_valid_spec.rb
  spec/lib/karafka/connection/pauses_manager_spec.rb
  spec/lib/karafka/pro/routing/features/pausing/contract_spec.rb
  spec/lib/karafka/pro/routing/features/pausing/topic_spec.rb
  spec/lib/karafka/pro/routing/features/pausing_spec.rb
  spec/lib/karafka/processing/coordinators_buffer_spec.rb
  spec/lib/karafka/routing/topic_spec.rb
Labels: feature, pro, routing, 2.1

#1540 v2.1.9
  CHANGELOG.md
Labels: 2.1

#1541 instrument rebalance callback
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/instrumentation/notifications.rb
  lib/karafka/patches/rdkafka/bindings.rb
  lib/karafka/version.rb
  spec/integrations/rebalancing/cooperative_sticky_without_assignment_spec.rb
Labels: instrumentation, 2.1

#1545 Always unsubscribe admin consumer
  CHANGELOG.md
  lib/karafka/admin.rb
Labels: bug, admin, 2.1

#1546 Unsubscribe long-living consumer client on close
  CHANGELOG.md
  lib/karafka/connection/client.rb
  lib/karafka/instrumentation/logger_listener.rb
  lib/karafka/instrumentation/notifications.rb
  spec/lib/karafka/instrumentation/logger_listener_spec.rb
Labels: bug, 2.1

#1547 cluster info based dynamic subscriptions
  spec/integrations/consumption/from_never_existing_topic_spec.rb
  spec/integrations/consumption/from_non_existing_topic_spec.rb
  spec/integrations/consumption/with_cluster_info_based_routes_spec.rb
  spec/integrations/routing/cluster_info_based_discovery_spec.rb
  spec/integrations/routing/runtime_routing_expansion_spec.rb
Labels: specs, internal, 2.1

#1554 increase watermark requests timeouts and do not unsubscribe long-lived
  CHANGELOG.md
  lib/karafka/admin.rb
  lib/karafka/base_consumer.rb
  lib/karafka/connection/client.rb
  lib/karafka/connection/proxy.rb
  lib/karafka/patches/rdkafka/bindings.rb
  lib/karafka/pro/iterator/tpl_builder.rb
  spec/lib/karafka/connection/proxy_spec.rb
Labels: bug, 2.1

#1557 always close consumer instance in specs
  spec/lib/karafka/connection/proxy_spec.rb
Labels: bug

#1561 Bump Rails + friends
  Gemfile.lock
  spec/integrations/pro/rails/rails7_pristine/just_a_dependency/Gemfile
  spec/integrations/pro/rails/rails7_pristine/just_a_dependency/railtie_setup_spec.rb
  spec/integrations/pro/rails/rails7_pristine/with-active_job_and_current_attributes/Gemfile
  spec/integrations/rails/rails7_pristine/just-a-dependency/Gemfile
  spec/integrations/rails/rails7_pristine/with-active_job/Gemfile
  spec/integrations/rails/rails7_pristine/with-active_job/railtie_setup_spec.rb
  spec/integrations/rails/rails7_pristine/with-active_job_and_current_attributes/Gemfile
  spec/integrations/rails/rails7_pristine/without-active_job/Gemfile
  spec/integrations/rails/rails7_pristine/without-active_job/railtie_setup_spec.rb
  spec/integrations/rails/rails7_pristine/without-active_job_rspec/Gemfile
Labels: 2.1

#1560 Disable auto-topic-create for admin
  CHANGELOG.md
  lib/karafka/admin.rb
Labels: admin, 2.1

#1564 introduce meta status #done? and make sure all done states work with it
  CHANGELOG.md
  lib/karafka/app.rb
  lib/karafka/connection/listener.rb
  lib/karafka/status.rb
  spec/integrations/shutdown/extremely_fast_stop_spec.rb
  spec/lib/karafka/app_spec.rb
  spec/lib/karafka/connection/listener_spec.rb
  spec/lib/karafka/status_spec.rb
Labels: bug, 2.1

#1565 fix negative dd reporting of stored lag
  CHANGELOG.md
  lib/karafka/instrumentation/vendors/datadog/metrics_listener.rb
Labels: bug, instrumentation, 2.1

#1567 Update signing cert
  certs/cert_chain.pem
Labels: internal, 2.1

#1571 Customize retry and timeouts for proxy
  CHANGELOG.md
  config/locales/errors.yml
  lib/karafka/connection/proxy.rb
  lib/karafka/contracts/config.rb
  lib/karafka/setup/config.rb
  spec/lib/karafka/contracts/config_spec.rb
Labels: enhancement, 2.1

#1572 karafka-rdkafka bump
  Gemfile.lock
Labels: internal, 2.1

#1574 v2.1.11
  CHANGELOG.md
  spec/integrations/instrumentation/error_callback_multiple_subscription_groups_spec.rb
Labels: 2.1

#1580 Fix DLQ + VP without intermediate marking may mark earlier message
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/pro/processing/strategies/dlq/default.rb
  lib/karafka/pro/processing/strategies/dlq/ftr.rb
  lib/karafka/version.rb
  spec/integrations/consumption/strategies/default/from_earliest_spec.rb
  spec/integrations/consumption/strategies/dlq/without_any_errors_spec.rb
  spec/integrations/pro/consumption/from_earliest_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/ftr_lrj_vp/without_intermediate_marking_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/ftr_vp/marking_without_intermediate_marking_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/lrj_vp/without_intermediate_marking_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/vp/marking_without_intermediate_marking_spec.rb
  spec/integrations/pro/consumption/strategies/ftr/custom_per_topic_spec.rb
  spec/integrations/pro/consumption/strategies/vp/without_intermediate_marking_spec.rb
  spec/integrations_helper.rb
Labels: pro, virtual partitions, dead letter queue, 2.1

#1582 v2.1.12
  CHANGELOG.md
Labels: 2.1

#1576 Support changing service_name in datadog integration
  lib/karafka/instrumentation/vendors/datadog/logger_listener.rb
  spec/integrations/instrumentation/vendors/datadog/logger_flow_spec.rb
  spec/support/vendors/datadog/logger_dummy_client.rb
Labels: instrumentation, 2.1

#1583 Support changing service_name in datadog integration (#1576)
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/instrumentation/vendors/datadog/logger_listener.rb
  lib/karafka/version.rb
  spec/integrations/instrumentation/vendors/datadog/logger_flow_spec.rb
  spec/support/vendors/datadog/logger_dummy_client.rb
Labels: instrumentation, 2.1

#1587 v2.1.13
  CHANGELOG.md
Labels: 2.1

#1591 Better patterns validation
  config/locales/pro_errors.yml
  lib/karafka/pro/routing/features/patterns/config.rb
  lib/karafka/pro/routing/features/patterns/contracts/consumer_group.rb
  spec/integrations/pro/routing/patterns/named_with_same_regexp_in_one_consumer_group_spec.rb
  spec/lib/karafka/pro/routing/features/patterns/contracts/consumer_group_spec.rb
Labels: pro, patterns
