Repository karafka/karafka, pull requests merged in 2023-05, with the labels that each got.

#1435 Virtual Offset Filtering
  CHANGELOG.md
  lib/karafka/pro/active_job/consumer.rb
  lib/karafka/pro/processing/coordinator.rb
  lib/karafka/pro/processing/filters/virtual_limiter.rb
  lib/karafka/pro/processing/filters_applier.rb
  lib/karafka/pro/processing/strategies/dlq/mom.rb
  lib/karafka/pro/processing/strategies/vp/default.rb
  lib/karafka/pro/processing/virtual_offset_manager.rb
  lib/karafka/processing/strategies/dlq_mom.rb
  spec/integrations/pro/consumption/strategies/aj/mom_vp/execution_on_failing_saturated_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/mom/at_most_once_skipping_on_error_poll_one_spec.rb
  spec/integrations/pro/consumption/strategies/vp/collapse_with_intermediate_marking_filtering_spec.rb
  spec/integrations/pro/consumption/strategies/vp/continuous_retry_in_collabse_with_filtering_spec.rb
  spec/integrations/pro/consumption/strategies/vp/pre_work_marking_retry_continuity_spec.rb
  spec/integrations/pro/consumption/strategies/vp/with_soft_marking_partial_error_spec.rb
  spec/lib/karafka/pro/active_job/consumer_spec.rb
  spec/lib/karafka/pro/processing/filters/virtual_limiter_spec.rb
  spec/lib/karafka/pro/processing/strategies_spec.rb
  spec/lib/karafka/pro/processing/virtual_offset_manager_spec.rb
Labels: in-progress, pro, virtual partitions, 2.1

#1436 1128 - Removed Pro::BaseConsumer in favor of BaseConsumer. (#1345)
  CHANGELOG.md
  lib/karafka/pro/base_consumer.rb
  spec/lib/karafka/pro/base_consumer_spec.rb
Labels: pro, 2.1

#1438 integration spec for reconnects
  spec/integrations/consumption/with_producer_disconnect_error_spec.rb
Labels: specs, internal

#1440 963 - Add support for Current Attributes to ActiveJob's adapter. (#1434)
  CHANGELOG.md
  Gemfile.lock
  lib/karafka.rb
  lib/karafka/active_job/consumer.rb
  lib/karafka/active_job/current_attributes.rb
  lib/karafka/active_job/current_attributes/loading.rb
  lib/karafka/active_job/current_attributes/persistence.rb
  lib/karafka/active_job/dispatcher.rb
  lib/karafka/pro/active_job/dispatcher.rb
  spec/integrations/consumption/strategies/aj_mom/parallel_current_attributes_coop_spec.rb
  spec/integrations/pro/consumption/strategies/aj/mom/parallel_current_attributes_coop_spec.rb
  spec/integrations/pro/rails/rails5_pristine/railtie_setup_spec.rb
  spec/integrations/pro/rails/rails6_pristine/railtie_setup_spec.rb
  spec/integrations/pro/rails/rails7_pristine/just_a_dependency/Gemfile
  spec/integrations/pro/rails/rails7_pristine/just_a_dependency/railtie_setup_spec.rb
  spec/integrations/pro/rails/rails7_pristine/with-active_job_and_current_attributes/Gemfile
  spec/integrations/pro/rails/rails7_pristine/with-active_job_and_current_attributes/active_job_run_spec.rb
  spec/integrations/rails/rails7_pristine/with-active_job_and_current_attributes/Gemfile
  spec/integrations/rails/rails7_pristine/with-active_job_and_current_attributes/active_job_run_spec.rb
  spec/lib/karafka/active_job/current_attributes_spec.rb
Labels: activejob, 2.1

#1441 Kubernetes HTTP liveness instrumentation
  lib/karafka/instrumentation/vendors/kubernetes/liveness_listener.rb
  spec/integrations/instrumentation/vendors/datadog/logger_flow_spec.rb
  spec/integrations/instrumentation/vendors/datadog/metrics_flow_spec.rb
  spec/integrations/instrumentation/vendors/kubernetes/liveness_all_good_spec.rb
  spec/integrations/instrumentation/vendors/kubernetes/polling_liveness_timeout_flow_spec.rb
  spec/integrations/instrumentation/vendors/kubernetes/processing_liveness_timeout_flow_spec.rb
  spec/lib/karafka/instrumentation/vendors/kubernetes/liveness_listener_spec.rb
Labels: instrumentation, 2.1

#1442 Better k8s and more specs
  lib/karafka/instrumentation/vendors/kubernetes/liveness_listener.rb
  spec/integrations/instrumentation/vendors/kubernetes/consuming_liveness_parallel_regular_flow_spec.rb
  spec/integrations/instrumentation/vendors/kubernetes/consuming_liveness_parallel_timeout_flow_spec.rb
  spec/integrations/instrumentation/vendors/kubernetes/consuming_liveness_timeout_flow_spec.rb
Labels: instrumentation, 2.1

#1444 Make sure max_messages and max_wait_time have references in errors.yml
  CHANGELOG.md
  config/locales/errors.yml
  spec/integrations/setup/max_messages_format_as_string_spec.rb
  spec/lib/karafka/contracts/topic_spec.rb
Labels: bug

#1446 Add missing error messages references
  config/locales/errors.yml
  spec/lib/karafka/contracts/config_spec.rb
  spec/lib/karafka/contracts/consumer_group_spec.rb
  spec/lib/karafka/contracts/topic_spec.rb
Labels: bug

#1447 v2.1.0
  CHANGELOG.md
Labels: 2.1

#1457 Fix `#retrying?` helper, enable phantom test
  lib/karafka/base_consumer.rb
  spec/integrations/consumption/with_branching_logic_on_retry_spec.rb
Labels: bug, 2.1

#1458 Fix `#retrying?` helper, enable phantom test (#1457)
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/base_consumer.rb
  lib/karafka/version.rb
  spec/integrations/consumption/at_most_once_on_error_spec.rb
  spec/integrations/consumption/retrying_flow_spec.rb
  spec/integrations/consumption/with_branching_logic_on_retry_spec.rb
  spec/integrations/pro/consumption/strategies/dlq/ftr/pipeline_with_delayed_dlq_spec.rb
  spec/integrations/pro/consumption/strategies/mom/ftr_vp/with_reversed_offsets_marking_and_error_spec.rb
  spec/integrations/pro/consumption/strategies/mom/vp/with_reversed_offsets_marking_and_error_spec.rb
  spec/integrations/specs_naming_spec.rb
Labels: bug, 2.1

#1462 Make sure to handle unknown_member_id when dealing with revoked partition on marking
  CHANGELOG.md
  lib/karafka/connection/client.rb
  spec/integrations/consumption/with_sync_mark_sa_consumed_after_revoke_spec.rb
  spec/support/data_collector.rb
Labels: bug, 2.1
