Repository karafka/karafka, pull requests merged in 2023-02, with the labels that each got.

#1296 Use common rspec locator base
  CHANGELOG.md
  Gemfile.lock
  karafka.gemspec
  lib/karafka/version.rb
  spec/support/rspec_locator.rb
Labels: 2.0, specs, internal

#1304 Ability to resize topics + wait fix
  CHANGELOG.md
  Gemfile.lock
  karafka.gemspec
  lib/karafka/admin.rb
  spec/integrations_helper.rb
  spec/lib/karafka/admin_spec.rb
Labels: 2.0, admin

#1301 [ISSUE-1300] fix: TOPIC_REGEXP
  config/locales/errors.yml
  lib/karafka/contracts.rb
  lib/karafka/contracts/consumer_group.rb
  lib/karafka/contracts/topic.rb
  spec/lib/karafka/contracts/consumer_group_spec.rb
  spec/lib/karafka/contracts/topic_spec.rb
Labels: 2.0, routing

#1305 Fix topic name validation (CandyFet)
  CHANGELOG.md
  config/locales/errors.yml
  lib/karafka/admin.rb
  lib/karafka/contracts.rb
  lib/karafka/contracts/consumer_group.rb
  lib/karafka/contracts/topic.rb
  spec/integrations/routing/with_namespace_collisions_spec.rb
  spec/lib/karafka/contracts/consumer_group_spec.rb
  spec/lib/karafka/contracts/topic_spec.rb
  spec/lib/karafka/routing/topic_spec.rb
  spec/spec_helper.rb
Labels: 2.0, routing

#1311 Improve non-critical error handling
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/connection/client.rb
  lib/karafka/time_trackers/poll.rb
  lib/karafka/version.rb
  spec/integrations/consumption/with_non_existing_topics_auto_create_spec.rb
  spec/integrations/consumption/with_non_existing_topics_no_auto_create_spec.rb
Labels: bug, enhancement, 2.0, internal

#1313 v2.0.32
  CHANGELOG.md
Labels: 2.0

#1315 Fix Karafka monitor is prematurely cached (#1314)
  CHANGELOG.md
  lib/karafka.rb
  lib/karafka/connection/client.rb
  lib/karafka/instrumentation/callbacks/error.rb
  lib/karafka/instrumentation/callbacks/statistics.rb
  lib/karafka/instrumentation/notifications.rb
  lib/karafka/setup/config.rb
  spec/integrations/setup/re_initialization_of_cached_resources_spec.rb
  spec/lib/karafka/instrumentation/callbacks/error_spec.rb
  spec/lib/karafka/instrumentation/callbacks/statistics_spec.rb
Labels: bug, 2.0, instrumentation

#1322 #1308 extra spec for short pause
  spec/integrations/pausing/pause_super_short_spec.rb
Labels: 2.0, specs, internal

#1328 Allow for disabling of strict_topics_namespacing validation
  CHANGELOG.md
  config/locales/errors.yml
  lib/karafka/contracts/consumer_group.rb
  lib/karafka/contracts/topic.rb
  lib/karafka/setup/config.rb
  spec/integrations/routing/with_namespace_collisions_without_strict_spec.rb
  spec/lib/karafka/contracts/consumer_group_spec.rb
  spec/lib/karafka/contracts/topic_spec.rb
Labels: 2.0, routing

#1333 Support Rails 7.1 batch AJ jobs
  CHANGELOG.md
  Gemfile.lock
  config/locales/errors.yml
  lib/active_job/queue_adapters/karafka_adapter.rb
  lib/karafka/active_job/dispatcher.rb
  lib/karafka/active_job/job_options_contract.rb
  lib/karafka/pro/active_job/dispatcher.rb
  lib/karafka/pro/active_job/job_options_contract.rb
  spec/lib/active_job/queue_adapters/karafka_adapter_spec.rb
  spec/lib/karafka/active_job/dispatcher_spec.rb
  spec/lib/karafka/active_job/job_options_contract_spec.rb
  spec/lib/karafka/pro/active_job/dispatcher_spec.rb
  spec/lib/karafka/pro/active_job/job_options_contract_spec.rb
Labels: 2.0, activejob, rails

#1336 Introduce ability to tag consumers and the process itself
  CHANGELOG.md
  Gemfile.lock
  karafka.gemspec
  lib/karafka/active_job/consumer.rb
  lib/karafka/base_consumer.rb
  lib/karafka/pro/active_job/consumer.rb
  lib/karafka/process.rb
  lib/karafka/version.rb
  spec/integrations/consumption/strategies/aj_mom/tagging_with_job_class_spec.rb
  spec/integrations/instrumentation/consumers_runtime_tagging_spec.rb
  spec/integrations/instrumentation/process_tagging_spec.rb
  spec/integrations/pro/consumption/strategies/aj_dlq_mom/tagging_with_job_class_spec.rb
Labels: 2.0, feature, instrumentation, web

#1346 Add embedded tag when Embedding API in use
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/embedded.rb
  lib/karafka/version.rb
  spec/integrations/embedding/tag_injection_spec.rb
Labels: enhancement, 2.0
