Repository karafka/karafka, pull requests merged in 2024-04, with the labels that each got.

#2020 fix docker compose
  .github/workflows/ci.yml
Labels: specs, internal

#2021 support custom errors
  CHANGELOG.md
  lib/karafka/instrumentation/logger_listener.rb
  spec/lib/karafka/instrumentation/logger_listener_spec.rb
Labels: instrumentation

#2022 Name used threads
  CHANGELOG.md
  lib/karafka/connection/listener.rb
  lib/karafka/embedded.rb
  lib/karafka/helpers/async.rb
  lib/karafka/instrumentation/logger_listener.rb
  lib/karafka/runner.rb
  spec/lib/karafka/helpers/async_spec.rb
  spec/lib/karafka/processing/worker_spec.rb
Labels: instrumentation

#2033 fix admin group seek
  CHANGELOG.md
  lib/karafka/admin.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group_topic_time_total_past_multi_partition_all_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group_topic_time_total_past_multi_partition_spec.rb
  spec/integrations_helper.rb
Labels: bug, admin

#2034 fix admin group seek, backport to 2.3
  CHANGELOG.md
  lib/karafka/admin.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group_topic_time_total_past_multi_partition_all_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group_topic_time_total_past_multi_partition_spec.rb
  spec/integrations_helper.rb
Labels: bug, admin

#2039 More group seeking specs
  spec/integrations/admin/consumer_groups/seek_consumer_group/few_partitions_few_topics_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group/time_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group/time_total_future_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group/time_total_past_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group/topic_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group/topic_time_total_past_multi_partition_all_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group/topic_time_total_past_multi_partition_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group/topic_time_total_past_spec.rb
Labels: specs, internal

#2040 stabilize alignment spec
  spec/integrations/cli/declaratives/align/align_existing_spec.rb
Labels: specs, internal

#2042 more admin seek specs
  spec/integrations/admin/consumer_groups/seek_consumer_group/mixed_time_and_real_offsets_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group/time_spec.rb
Labels: specs, internal

#2046 pattern dlq vp err str spec
  spec/integrations/pro/consumption/strategies/dlq/vp/patterned_custom_strategy_based_flow_spec.rb
Labels: virtual partitions, dead letter queue, patterns

#2050 Map update
  lib/karafka/setup/attributes_map.rb
Labels: api-sync

#2053 total crash spec
  bin/integrations
  spec/integrations/instrumentation/post_errors_instrumentation_error_spec.rb
Labels: specs

#2057 Protect rdkafka thread callbacks flow from errors
  CHANGELOG.md
  lib/karafka/instrumentation/callbacks/error.rb
  lib/karafka/instrumentation/callbacks/oauthbearer_token_refresh.rb
  lib/karafka/instrumentation/callbacks/rebalance.rb
  lib/karafka/instrumentation/callbacks/statistics.rb
  lib/karafka/instrumentation/logger_listener.rb
  spec/lib/karafka/instrumentation/callbacks/error_spec.rb
  spec/lib/karafka/instrumentation/callbacks/oauthbearer_token_refresh_spec.rb
  spec/lib/karafka/instrumentation/callbacks/rebalance_spec.rb
  spec/lib/karafka/instrumentation/callbacks/statistics_spec.rb
  spec/lib/karafka/instrumentation/logger_listener_spec.rb
Labels: enhancement, instrumentation

#2065 Support migrating via aliases and plan with aliases usage
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/cli/topics/align.rb
  lib/karafka/cli/topics/plan.rb
  lib/karafka/version.rb
  spec/integrations/cli/declaratives/align/aliased_aligned_spec.rb
  spec/integrations/cli/declaratives/align/aligned_spec.rb
  spec/integrations/cli/declaratives/align/existing_spec.rb
  spec/integrations/cli/declaratives/align/incorrectly_spec.rb
  spec/integrations/cli/declaratives/align/nothing_spec.rb
  spec/integrations/cli/declaratives/create/empty_spec.rb
  spec/integrations/cli/declaratives/create/new_spec.rb
  spec/integrations/cli/declaratives/create/non_empty_but_opted_out_spec.rb
  spec/integrations/cli/declaratives/create/skip_existing_spec.rb
  spec/integrations/cli/declaratives/delete/empty_spec.rb
  spec/integrations/cli/declaratives/delete/existing_spec.rb
  spec/integrations/cli/declaratives/delete/opted_out_spec.rb
  spec/integrations/cli/declaratives/delete/skip_non_existing_spec.rb
  spec/integrations/cli/declaratives/delete/skip_not_defined_spec.rb
  spec/integrations/cli/declaratives/migrate/existing_more_partitions_spec.rb
  spec/integrations/cli/declaratives/migrate/existing_no_change_spec.rb
  spec/integrations/cli/declaratives/migrate/existing_no_topic_spec.rb
  spec/integrations/cli/declaratives/migrate/inactive_spec.rb
  spec/integrations/cli/declaratives/migrate/opted_out_spec.rb
  spec/integrations/cli/declaratives/plan/when_no_topics_at_all_spec.rb
  spec/integrations/cli/declaratives/plan/when_same_config_under_aliases_no_change_spec.rb
  spec/integrations/cli/declaratives/plan/when_same_config_under_aliases_with_change_spec.rb
  spec/integrations/cli/declaratives/plan/when_same_config_under_aliases_with_proper_change_spec.rb
  spec/integrations/cli/declaratives/plan/when_with_config_spec.rb
  spec/integrations/cli/declaratives/plan/when_with_no_changes_needed_spec.rb
  spec/integrations/cli/declaratives/plan/when_with_partitions_spec.rb
  spec/integrations/cli/declaratives/plan/when_without_changes_spec.rb
  spec/integrations/cli/declaratives/repartition/empty_spec.rb
  spec/integrations/cli/declaratives/repartition/less_present_spec.rb
  spec/integrations/cli/declaratives/repartition/more_present_spec.rb
  spec/integrations/cli/declaratives/repartition/opted_out_spec.rb
  spec/integrations/cli/declaratives/reset/existing_spec.rb
Labels: bug, admin, declaratives

#2066 Supports moving offset to `:earliest` and `:latest`
  CHANGELOG.md
  lib/karafka/admin.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group/to_earliest_latest_par_partition_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group/to_earliest_on_topic_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group/to_earliest_on_topic_via_false_spec.rb
  spec/integrations/admin/consumer_groups/seek_consumer_group/to_latest_spec.rb
Labels: admin

#2068 Spec for minitest usage
  spec/integrations/specs_naming_spec.rb
  spec/integrations/testing/minitest_pristine/Gemfile
  spec/integrations/testing/minitest_pristine/assertions.rb
  spec/integrations/testing/minitest_pristine/test_flow_with_marking_spec.rb
Labels: specs

#2070 use base64 from gem
  CHANGELOG.md
  Gemfile.lock
  karafka.gemspec
Labels: api-sync

#2071 one more spec for marking in transaction and piping
  spec/integrations/pro/consumption/piping/with_key/transactional_with_marking_spec.rb
Labels: specs, transactions

#2072 Ensure key and headers deserialization works with karafka-testing helpers
  Gemfile.lock
  spec/integrations/testing/minitest_pristine/assertions.rb
Labels: specs
