Repository karafka/karafka, pull requests merged in 2024-06, with the labels that each got.

#2123 bump-deps-2024-06-03
  Gemfile.lock
Labels: dependencies

#2124 fix invalid install reference
  CHANGELOG.md
  lib/karafka.rb
  lib/karafka/cli/install.rb
  spec/integrations/installation/standalone_nested_boot_file_pristine/Gemfile
  spec/integrations/installation/standalone_nested_boot_file_pristine/install_spec.rb
  spec/lib/karafka/cli/install_spec.rb
  spec/lib/karafka_spec.rb
Labels: bug

#2129 Provide ability to use custom VP reducers
  CHANGELOG.md
  config/locales/pro_errors.yml
  lib/karafka/pro/processing/partitioner.rb
  lib/karafka/pro/routing/features/virtual_partitions/config.rb
  lib/karafka/pro/routing/features/virtual_partitions/contracts/topic.rb
  lib/karafka/pro/routing/features/virtual_partitions/topic.rb
  spec/integrations/pro/consumption/strategies/vp/round_robin_with_direct_reducer_spec.rb
  spec/lib/karafka/pro/routing/features/virtual_partitions/contracts/topic_spec.rb
  spec/lib/karafka/pro/routing/features/virtual_partitions/topic_spec.rb
Labels: enhancement, pro, virtual partitions

#2131 rails7 ruby 3.4 fixes
  spec/integrations/installation/with_rails71_pristine/Gemfile
  spec/integrations/installation/with_rails7_pristine/Gemfile
Labels: activejob, internal

#2139 Propagate fatal errors faster
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/connection/client.rb
  lib/karafka/version.rb
Labels: bug

#2142 Fix Bundler dir permissions issue
  .github/workflows/ci.yml
Labels: bug

#2141 bump-deps-2024-06-17
  Gemfile.lock
Labels: dependencies

#2150 improve embedding mode
  CHANGELOG.md
  lib/karafka/embedded.rb
  spec/integrations/embedding/puma_poro/config/puma.rb
  spec/integrations/embedding/puma_single_poro/Gemfile
  spec/integrations/embedding/puma_single_poro/config/app.rb
  spec/integrations/embedding/puma_single_poro/config/puma.rb
  spec/integrations/embedding/puma_single_poro/flow_spec.rb
  spec/integrations/embedding/puma_with_worker_poro/Gemfile
  spec/integrations/embedding/puma_with_worker_poro/config/app.rb
  spec/integrations/embedding/puma_with_worker_poro/config/puma.rb
  spec/integrations/embedding/puma_with_worker_poro/flow_spec.rb
  spec/lib/karafka/embedded_spec.rb
Labels: enhancement

#2155 enhance spec checks
  spec/integrations/pro/consumption/transactions/lost_assignment_with_offset_storage_spec.rb
Labels: specs, internal

#2157 bump-deps-2024-06-29
  Gemfile.lock
Labels: dependencies
