Repository karafka/karafka, pull requests merged in 2024-05, with the labels that each got.

#2077 add expired execution spec
  spec/integrations/consumption/finishing_job_after_max_poll_exceeded_spec.rb
Labels: specs

#2078 Extra spec illustrating that pausing won't bypass max.poll
  spec/integrations/consumption/pausing_not_unlocking_spec.rb
Labels: specs

#2079 karafka should allow for custom routing features
  spec/integrations/routing/topic_custom_attributes_spec.rb
Labels: specs, routing

#2081 fix invalid active defaults application
  CHANGELOG.md
  lib/karafka/routing/topic.rb
  spec/integrations/routing/and_cli_validations_for_exclusions_spec.rb
  spec/integrations/routing/and_cli_validations_for_inclusions_spec.rb
  spec/integrations/routing/and_cli_validations_for_many_inclusions_spec.rb
  spec/integrations/routing/with_active_false_overwritten_spec.rb
  spec/integrations/routing/with_active_true_overwritten_spec.rb
  spec/integrations/routing/with_nameless_subscription_groups_spec.rb
  spec/integrations/routing/with_subscription_groups_block_based_spec.rb
  spec/integrations/routing/with_subscription_groups_chaotic_order_spec.rb
  spec/integrations/routing/with_symbol_based_subscription_group_spec.rb
  spec/integrations/routing/with_the_simple_routes_style_spec.rb
Labels: bug, routing

#2084 more seek specs
  spec/integrations/seek/back_with_reset_and_mark_again_spec.rb
  spec/integrations/seek/back_without_reset_and_mark_again_spec.rb
  spec/integrations/seek/backward_from_consumer_spec.rb
  spec/integrations/seek/in_a_loop_spec.rb
  spec/integrations/seek/to_a_given_offset_from_consumer_spec.rb
  spec/integrations/seek/to_non_existing_future_spec.rb
  spec/integrations/seek/to_time_before_start_spec.rb
  spec/integrations/seek/with_time_spec.rb
Labels: specs

#2086 illustrate latest first error seek
  CHANGELOG.md
  lib/karafka/setup/attributes_map.rb
  spec/integrations/consumption/error_on_first_latest_and_restart_spec.rb
  spec/integrations/consumption/error_on_first_latest_marked_and_restart_spec.rb
  spec/integrations_helper.rb
Labels: specs, internal

#2091 Ensure pristine WaterDrop can run
  Gemfile.lock
  spec/integrations/installation/waterdrop_run_pristine/Gemfile
  spec/integrations/installation/waterdrop_run_pristine/run_spec.rb
Labels: specs, internal

#2093 Fix activejob karafka_options inheritance
  CHANGELOG.md
  lib/karafka/active_job/job_extensions.rb
  spec/integrations/consumption/strategies/aj_mom/options_override_and_inheritance_spec.rb
  spec/integrations/pro/consumption/strategies/aj/mom/with_multiple_custom_partitioners_spec.rb
Labels: bug, activejob

#2100 Illustrate compression types support
  spec/integrations/production/compression_different_no_conflict_spec.rb
Labels: specs

#2101 Spec to check that keyless are rejected on compacted topics
  spec/integrations/production/reject_no_key_message_when_compacted_spec.rb
Labels: specs

#2103 validate activejob alternative producer option
  CHANGELOG.md
  Gemfile.lock
  config/locales/errors.yml
  lib/karafka/pro/active_job/job_options_contract.rb
  lib/karafka/version.rb
  spec/lib/karafka/pro/active_job/job_options_contract_spec.rb
Labels: activejob, pro

#2106 Fix invalid time seek in higher offsets
  CHANGELOG.md
  lib/karafka/connection/client.rb
  spec/integrations/seek/to_a_given_offset_from_consumer_on_higher_partition_spec.rb
  spec/integrations/seek/to_time_before_start_on_higher_partition_spec.rb
Labels: bug

#2109 Add some more error codes to early report
  lib/karafka/connection/client.rb
Labels: enhancement

#2112 use config injector in the runner
  lib/karafka/runner.rb
Labels: refactor

#2113 remove empty default async thread name
  CHANGELOG.md
  lib/karafka/helpers/async.rb
Labels: refactor

#2115 Retry transport and few other errors to retry when in proxy
  CHANGELOG.md
  lib/karafka/connection/proxy.rb
Labels: enhancement
